### ISSUE TITLE
Change drafting for 'Preferred Country Chapter'

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#105]
![image](https://user-images.githubusercontent.com/390030/32573379-8f50b510-c4ac-11e7-859d-0ee613f32dd6.png)

As far I remember when we discussed this with @peterspdx, we decided to:

* Ask for Country of residence
* Keep this optional (as far there isn't any automatic assumption of your residence country and your participation on a particular Chapter) -- is it possible to keep this field editable by the user later on?

**Comment by peterspdx** [comment]
Actually, Rob and I discussed and ended up agreeing otherwise. @robmyers what do your notes reflect? @claudioruiz One reason for handling it this way is because it's conceivable someone is outside of their preferred country (conducting research or whatever) but still wants to be part of their home country chapter. I believe we settled on a couple of questions about "location" loosely defined, not just the one noted.

**Comment by claudioruiz** [comment]
I see. 

But I'm still having problems with _setting in stone_ your Country Chapter on your application as a member as far there is not formal requirement for this. You can perfectly being a member without having connection with your local (or remote) Chapter. Adding this to the form appears to be otherwise.

**Comment by peterspdx** [comment]
I don't think it suggests it's in stone, it's merely a statement of interest as phrased. Rob and I also discussed allowing people to choose more than one (I live in Canada while writing my thesis but I'm from Chile and want to participate in both Chapters though I realize I have to choose one for puposes of participating in governance matters.

And I don't see how asking them for their Chapter of interest is any more of a commitment then relegating them automatically to the one where they are currently located. Isn't the net effect the same?

How about we three talk this morning so that coding section can be completed. I'll send an invite.

**Comment by claudioruiz** [comment]
@peterspdx yeah, let's solve it on a call. Thanks
