### ISSUE TITLE
Same CCID for Institutional and Individual Applications Returns "Already Approved"

### ISSUE THREAD

**Issue by meredithjacob** [creativecommons/commoners#165]
When I go to sign my institution up as an Institutional Member, I get instructions that I need a CCID.  If I use my existing "meredithjacob" CCID, I get an "already approved" message, instead of entering the application process.  Should I create a new institution-specific CCID, or is this a bug?

**Comment by claudioruiz** [comment]
@robmyers can you check this out? I want to be 100% sure about the workflow for Institutional Applications before sending the official mail to them.

**Comment by robmyers** [comment]
Institutions need a separate account.

The logic behind this is that Institutions cannot Vouch but Interim Membership Council members can.

So, with apologies, you'll need another CCID login for this. Think personal and work Twitter Accounts rather than Personal and Business Facebook pages.

If you'd rather use this email for that let me know and we can swap them.

**Comment by meredithjacob** [comment]
Thanks. Separate is fine, just wanted to understand the system.

Meredith Jacob
(443)745-5366

On Jan 17, 2018, at 21:34, Rob Myers <notifications@github.com<mailto:notifications@github.com>> wrote:


Institutions need a separate account.

The logic behind this is that Institutions cannot Vouch but Interim Membership Council members can.

So, with apologies, you'll need another CCID login for this. Think personal and work Twitter Accounts rather than Personal and Business Facebook pages.

If you'd rather use this email for that let me know and we can swap them.
