### ISSUE TITLE
List of members is acting weird

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/commoners#258]
Suddenly, we have way more people listed than members of the network. https://network.creativecommons.org/members/

There's some duplicate entries (see [this](https://network.creativecommons.org/members/arismaro/) and [this](https://network.creativecommons.org/members/aristarik/)) and, most weirdly, there are names there who are definitely not a member but part of the notification issue we had.

**Comment by robmyers** [comment]
I've done a thorough check of the data and no non-members should appear in the form for choosing Vouchers. So that's good.

The duplicate entry is weird. One user has a username that is the same as another user's email address. The duplicate should not be being displayed as it has not been approved yet.

So the underlying problem is that the code for excluding un-approved / non-member accounts from that list is broken. It was very carefully tested code, so the breakage is disturbing.

I am going to dig in and see what has changed.

**Comment by robmyers** [comment]
The users who were part of the issue had their roles removed, the code wasn't catching this.

The duplicates were hopefully all duplicate applications only one of which was approved.

I have updated the code to exclude declined members.

**Comment by claudioruiz** [comment]
good, now the list of members appears to be right. Thanks
