### ISSUE TITLE
Search fields does not remember previous search, while it does display the previous search.

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/commoners#263]
Steps to reproduce

Search for a member (e.g. Ryan) and click search
![image](https://user-images.githubusercontent.com/5627431/44255088-3014b600-a205-11e8-9223-07ae1ee02aec.png)
'Ryan' is still filled in the search field. Click search again. Search field does not remember the name that is previously searched.
![image](https://user-images.githubusercontent.com/5627431/44255118-428eef80-a205-11e8-97b6-7164db431a15.png)

**Comment by hugosolar** [comment]
Problem fixed in commit https://github.com/creativecommons/commoners/commit/cf7db957210923398fcaeeb55ca03388b32afa7a
But we still have a weird behavior that I have to check deeply because the results aren't consistent between ajax and post search

**Comment by hugosolar** [comment]
The search result dispairing between ajax and "post" search was fixed in https://github.com/creativecommons/commoners/commit/78d4c1a1ac844bf85a9125294a7907c4fc85a485 
The problem happens when members filter lost its context and avoid the approved members' filter.
Closing this issue because it was fixed in #307
