### ISSUE TITLE
Make Insitutional Member Profiles Visible If Not Logged In

### ISSUE THREAD

**Issue by robmyers** [creativecommons/commoners#35]
Will need to hook code that disables profiles and profile fields.

**Comment by claudioruiz** [comment]
is this solved? @robmyers

**Comment by hugosolar** [comment]
- Public Institutional members list. pull request https://github.com/creativecommons/commoners/commit/7ac554d31c57abc4ef5cee6308c2c4dfb8c2e16d
- Public Institutional member profile. pull request https://github.com/creativecommons/commoners/commit/a1e297411091ffab12cb2bf044de205b3e9f35e7

I will add an option in the main menu for non-logged users in order to see the institutional members list
