### ISSUE TITLE
View Profile button on CC network chapter webpages

### ISSUE THREAD

**Issue by brigittevezina** [creativecommons/commoners#409]
## Description
<When I click on the View Profile buttons of the CC Chapter leads in any country, I am brought back to the Network homepage.>

## Reproduction

1. 
2. 
3. 
4. See error.

## Expectation
<I would like to have the links between the "view profile" buttons and the profiles pages fixed.>

## Environment

 - Device: (_eg._ iPhone Xs; laptop) laptop
 - OS: (_eg._ iOS 13.5; Fedora 32) Catalina
 - Browser: (_eg._ Safari; Firefox) Chrome
 - Version: (_eg._ 13; 73) ?
 - Other info: (_eg._ display resolution, ease-of-access settings)

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by hugosolar** [comment]
The profile screen is not public so users need to be logged in in order to see a profile.
This workflow is solved in the new design, because it doesn't show the link unless the users are logged in
![Screen Shot 2021-02-05 at 8 52 43 AM](https://user-images.githubusercontent.com/894708/107030525-8c7e3e00-678f-11eb-9aa6-07effa7b118e.png)
