### ISSUE TITLE
[Bug] User unable to see vouching requests

### ISSUE THREAD

**Issue by xolotl** [creativecommons/commoners#438]
## Description
CCID user [Pedro Lana](https://network.creativecommons.org/wp-admin/user-edit.php?user_id=3525) has an active CCGN vouching request, but it does not appear when they are logged in with the CCID.

I'm not sure if this is related, but I noticed that Pedro's profile does not show up like other users, so for example, one can see [the profile for Leonardo Foletto](https://network.creativecommons.org/members/leonardofoletto/), someone who successfully vouched for the same prospective member, but such a profile is not available for Pedro. Even [Leonardo's user ID redirects to their profile](https://network.creativecommons.org/members/178/), but [Pedro's user ID](https://network.creativecommons.org/members/3525/) does not.

## Expectation
Pedro should be able to log in to network.creativecommons.org using their CCID and see active vouching requests.

**Comment by xolotl** [comment]
FWIW, Pedro reports that when they are logged in, no matter the device, they see this when viewing vouching requests: ![Screenshot_20230105-223753](https://user-images.githubusercontent.com/997548/210916833-ea23a18c-133e-4c9c-80e2-083aea366aef.png)

**Comment by possumbilities** [comment]
I'm unsure initially if the profile behavior you have described is related to this or not, since my own profile behaves the same way, but I do not get the same page when viewing the Vouch page, as indicated by their screenshot. 

Whether they had a Vouching request or not, the screenshot they've provided is not the view shown when logged in. Instead, they should see this: 
<img width="1212" alt="Screen Shot 2023-01-09 at 1 05 52 PM" src="https://user-images.githubusercontent.com/109087089/211388046-ccd34768-a5dd-41f8-8c8e-7b5c75715394.png">

The missing green bar, and prompt to login seems to indicate that for this page the site is either not registering their logged-in state, or that this page is not rendering as it should to match that state. 

@xolotl Could you find out if they can get to their own profile to edit it, or navigate to any other "logged in" only page after logging in?

When they click the "Log in" link on that Vouch page they shared a screenshot of, and then proceed to login through CCID, when it redirects them back to the Vouch page does it still ask them to log in?

I suspect this could be any number of issues, but my first instinct is that it's some kind of cache issue, whereby they are being served the cached state of the logged out Vouch page, even when logged in. 

If they could provide more info I might be able to dig further, and narrow down some possible causes.

**Comment by xolotl** [comment]
The immediate need for this user to log in has passed, so let's only return attention if they return with more info and a need to authenticate.

**Comment by xolotl** [comment]
Closing as user reports via email that they are now able to log in. Unclear what the issue was.
